### PR TITLE
`server.init` should be awaited

### LINKED ISSUE #62: `server.init` should be awaited
Changed in this PR: https://github.com/sveltejs/kit/pull/6179

### PR DESCRIPTION
**Pull request by FlippingBinary**
Fixes #62.

### CODE REVIEW

**Comment by geoffrich** [comment]
Were you able to test this on Azure or via the SWA CLI? I'd want to make sure that top-level await doesn't cause any issues.

**Comment by FlippingBinary** [comment]
I don't have an Azure test environment set up to take custom adapters and I must have made an error during manual testing. This pull request isn't ready. 

It could use `.catch((e) => {throw e})` syntax instead of `await`. That does build and work in the SWA CLI.

**Comment by geoffrich** [comment]
Here's how adapter-netlify does it: https://github.com/sveltejs/kit/blob/d0b51aeaed669991835cbb527b29f9ba4e654489/packages/adapter-netlify/src/serverless.js#L12-L20

We need to make sure `server.init` has resolved before we run the SK request handler.

**Comment by geoffrich** [comment]
Closed by #128

**Pull request closed without merging**
